### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fangaiqing** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#1]
when I connected the RC to the mobile device , the demo crashed immediately.
![crash](https://cloud.githubusercontent.com/assets/16395946/11952099/f830959a-a8d0-11e5-8653-435b56088a18.jpg)

**Comment by SilverChangjian** [comment]
It seems that the .so files have not been imported correctly. Please check the configuration of your project.

**Comment by fangaiqing** [comment]
I used your demo......

**Comment by dji-dev** [comment]
Hi please try the new updated Android FPVDemo, it's upgrade to SDK 3.0 now. Thanks!

**Comment by dji-dev** [comment]
Since I don't get your reply, and the FPVDemo is already updated to SDK 3.2.1, it should fix your problem. Close this issue now.
