### ISSUE TITLE
missing graphic files

### ISSUE THREAD

**Issue by ytlee** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#14]
Missing the following files
back_button_disable.png
back_button_normal.png
back_button_press.png
selector_back_button.xml

IN THE EXAMPLE FILE

**Comment by dji-dev** [comment]
Hi! Please check this link to get the files: https://github.com/DJI-Mobile-SDK/Android-FPVDemo/tree/master/FPVDemo/app/src/main/res/drawable, they are actually in the FPVDemo/app/src/main/res/drawable path.

**Comment by oliverou** [comment]
Since there is no response from @ytlee for a long time, close this issue now.
