### ISSUE TITLE
Issues with the Phantom 3 Standard

### ISSUE THREAD

**Issue by Bumler** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#15]
The app does not seem to work completely with Phantom 3 Standard. While I am able to see through the drones camera all other functionality of the app seems to be lost. I.e. capture and video mode do not save to the drone's SD card and instead of saying the model of drone connected it says disconnected (it also puts up two toast messages that say disconnected upon opening the app). Lastly, if you open the app connected to the controller's wi-fi it will say that the SDK registration failed.

More generally I was curious if DJI or anyone have put out tutorials specifically on coding for drones where you have only a wi-fi connection to the controller. Alternatively is it possible to somehow hardwire the phone into the phantom 3 standard controller.

Any help is greatly appreciated.

**Comment by dji-dev** [comment]
Hi, the Android FPVDemo works well with Phantom 3 Standard after testing by us. Could provide more info for us to check the problem?

* Which Android Device and Android System version you are using?
* Which Android Studio version you are using?

Thanks!

**Comment by Bumler** [comment]
Hello thanks for the fast reply,

I am using an LG G3 and am on version 6.0.

As of my last test I am on Android studio version 2.1.2 although I have
downloaded 2.1.3 and will try that later today (although I don't
antiplcipate it will make a difference).

Lastly to try and ensure that the error isn't something on my end I've gone
through all my FPVdemo files (java, xml and manifest) and compared them to
the github project using a compare tool. I made sure that my files only
differ in package names and API key.

Henry

**Comment by dji-dev** [comment]
Hi, thanks for your info. We have updated the Android FPVDemo, please pull the latest code of FPVDemo from Github and try again, for tutorial, you can check here: https://developer.dji.com/mobile-sdk/documentation/android-tutorials/FPVDemo.html 

Hope this help!

**Comment by Bumler** [comment]
That was extremely helpful! Something that was exacerbating my issue was that my device was unable to connect and register the SDK on the wifi I was using but I've heard this is a known issue.

**Comment by oliverou** [comment]
This issues is resolved, close it now.
