### ISSUE TITLE
FPVDemo no video

### ISSUE THREAD

**Issue by wangweifrank** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#17]
I have a question about Dji mobile on Android System. 

I used a Android device and run Dji go ,then set open EXT port and App-output-mode from LB to EXT ,The device can display video.

However when I run the FPVDemo ( download from the GitHub DJI-SDK ) by Android Studio ,it dosen’t work, I can not see anything from the preview.

First, I can make sure that the app is register success and jump to the MainActivity.class, 
Second, the CameraReceivedVideoDataCallback has no data callback;
Third, the environment like that.

Env:Huawei M3 + A3 + LightBridge 2 + 禅思X5 + S900

What do I need to set in this demo to display the video ?

**Comment by adityajain07** [comment]
Hi, were you able to fix it? Having the same issue.

**Comment by CyrilSiman** [comment]
Hi same problem with my galaxy S8 and my Osmo Mobile, no preview. 

Anyone can tell me if this sample works with the Osmo Mobile and the smartphone camera ? (Maybe this sample only works with Camera provided by dji product).

The DJI documentation talk about camera for osmo product but don't specifiy if it also works with the mobile version.

**Comment by CyrilSiman** [comment]
Hi, i have answer m'y own question. On this sample the camera permission isn't used. Without it we can't use caméra API. So this sample works only with dji caméra product.

**Comment by oliverou** [comment]
Hi @wangweifrank, currently, the DJI Android SDK and FPVDemo don't support S900, you can check this table on developer website for details: <http://developer.dji.com/mobile-sdk/documentation/introduction/product_introduction.html#supported-products>. 

@CyrilSiman , the FPVDemo doesn't support Osmo Mobile too, but you can check the Android Github Sample Code: <https://github.com/dji-sdk/Mobile-SDK-Android/tree/master/Sample%20Code> for help.
