### ISSUE TITLE
Big problem with flyzone | DJI SDK

### ISSUE THREAD

**Issue by lillogoal** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#21]
Hi to all,
I'm developping an mobile application with DJI SDK in Android studio.
I use Fabric for report crash
I usually get crash reports of this kind:
1) Fatal Exception: net.sqlcipher.database.SQLiteException: attempt to write a readonly database       at net.sqlcipher.database.SQLiteDatabase.native_rawExecSQL(Unknown Source)       at net.sqlcipher.database.SQLiteDatabase.rawExecSQL(Unknown Source)       at dji.midware.data.forbid.util.FlyforbidUtils.generateConfuMixDb(Unknown Source)       at dji.midware.data.forbid.db.FlyfrbPolygonMainDbManager.getDb(Unknown Source)       at dji.midware.data.forbid.db.FlyfrbBaseDbManager.deleteAll(Unknown Source)       at dji.internal.geofeature.flyforbid.FlyfrbPolygonDataUpdateManager$1.onSuccess(Unknown Source)       at dji.internal.geofeature.flyforbid.FlyfrbPolygonDataUpdateManager$1.onSuccess(Unknown Source)       at dji.thirdparty.afinal.http.HttpHandler.onProgressUpdate(Unknown Source)       at dji.thirdparty.afinal.core.AsyncTask$InternalHandler.handleMessage(Unknown Source)       at android.os.Handler.dispatchMessage(Handler.java:102)       at android.os.Looper.loop(Looper.java:154)       at android.app.ActivityThread.main(ActivityThread.java:6121)       at java.lang.reflect.Method.invoke(Method.java)       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

2) Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void net.sqlcipher.database.SQLiteDatabase.dbopen(java.lang.String, int) (tried Java_net_sqlcipher_database_SQLiteDatabase_dbopen and Java_net_sqlcipher_database_SQLiteDatabase_dbopen__Ljava_lang_String_2I)       at net.sqlcipher.database.SQLiteDatabase.dbopen(Unknown Source)       at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(Unknown Source)       at net.sqlcipher.database.SQLiteDatabase.openDatabase(Unknown Source)       at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(Unknown Source)       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(Unknown Source)       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(Unknown Source)       at dji.thirdparty.afinal.FinalDb.generateDb(Unknown Source)       at dji.thirdparty.afinal.FinalDb.<init>(Unknown Source)       at dji.thirdparty.afinal.FinalDb.getInstance(Unknown Source)       at dji.thirdparty.afinal.FinalDb.create(Unknown Source)       at dji.thirdparty.afinal.FinalDb.create(Unknown Source)       at dji.midware.data.forbid.db.FlyforbidDbManager.getDb(Unknown Source)       at dji.midware.data.forbid.db.FlyfrbBaseDbManager.<init>(Unknown Source)       at dji.midware.data.forbid.db.FlyforbidDbManager.<init>(Unknown Source)       at dji.midware.data.forbid.db.FlyforbidDbManager.init(Unknown Source)       at dji.midware.data.forbid.DJIFlyForbidController.<init>(Unknown Source)       at dji.midware.data.forbid.DJIFlyForbidController.getInstance(Unknown Source)       at dji.internal.geofeature.flyforbid.FlyforbidUpdateService.onCreate(Unknown Source)       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3192)       at android.app.ActivityThread.-wrap5(ActivityThread.java)       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568)       at android.os.Handler.dispatchMessage(Handler.java:102)       at android.os.Looper.loop(Looper.java:154)       at android.app.ActivityThread.main(ActivityThread.java:6121)       at java.lang.reflect.Method.invoke(Method.java)       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

3) Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference       at dji.midware.data.forbid.db.FlyfrbPolygonMainDbManager.getDb(Unknown Source)       at dji.midware.data.forbid.db.FlyfrbBaseDbManager.findAll(Unknown Source)       at dji.internal.geofeature.flyforbid.FlyfrbPolygonDataUpdateManager.<init>(Unknown Source)       at dji.internal.geofeature.flyforbid.FlyforbidUpdateService$1.run(Unknown Source)       at java.lang.Thread.run(Thread.java:761)

I'm using the last version of dji sdk.
So how can i solve this problems ? 

THANKS IN ADVANCE
--

**Comment by dji-dev** [comment]
Will go ahead and close this ticket as current version should not have this problem any more.
Please feel free to reopen if the problem still exists.
Thanks!
