### ISSUE TITLE
Demo does not work with local setup of Lightbridge 2 + A3 + X3

### ISSUE THREAD

**Issue by varadgunjal** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#22]
Since my Phantom 4 is currently grounded, I tried to test this demo with a local setup of a controller connected via Lightbridge 2 to an A3 controller, with a Zenmuse X3 gimbal camera. The list here - http://developer.dji.com/mobile-sdk/documentation/introduction/product_introduction.html#supported-products - says this setup is supported. 
I do get a `Register Success` message. However when I move to the next screen , I only see the 4 buttons and no video feed. Any ideas what could be going wrong? Or should I stick to using this with an able drone only?

![screenshot_20171102-015040](https://user-images.githubusercontent.com/7705170/32286471-ea58dcd0-bf70-11e7-8fc3-304f431569c5.png)

**Comment by oliverou** [comment]
Hi @varadgunjal , currently, the FPVDemo doesn't support LB2+A3+X3, please check the Android SDK Sample instead: <https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/camera/VideoFeederView.java>

**Comment by oliverou** [comment]
Hi @varadgunjal, will close this ticket for now. If you still have problems on the FPVDemo, please feel free to reopen it. Thanks!
