### ISSUE TITLE
不能够拍照，报错： "Not Support"

### ISSUE THREAD

**Issue by mizhoux** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#28]
设备为 **精灵4 Pro**，目前 SDK 的拍照功能不能使用，调用 `captureAction` 时都是 "Not Support"；回退到之前的 SDK 版本（4.2.1）也还是不能，是否是因为设备固件升级所导致的问题？

**Comment by dji-dev** [comment]
Hi @mizhoux , we have tested the FPVDemo on Phantom 4 Pro, the capture feature is available on the latest Android SDK 4.5.1. Please check if you have logined and activated your application before you use the capture feature, for more details, you can check the tutorial: <https://developer.dji.com/mobile-sdk/documentation/android-tutorials/index.html#application-activation-and-aircraft-binding-in-china>

**Comment by mizhoux** [comment]
I did have logined and activated, as the evidence of that is the video recording feature is  available. It was since I updated firmware, the capture feature started to be not available.

**Comment by mizhoux** [comment]
The function is ok now. It's interesting because I did nothing but opened the DJI Go app, then the capture feature was available in this FPVDemo.
