### ISSUE TITLE
Auto Focus

### ISSUE THREAD

**Issue by il421** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#32]
Hey,

I need to implement autofocus fo my video app. I use this: camera.getCamera().setFocusMode(SettingsDefinitions.FocusMode.AUTO, null);

where exactly, or at what moment I need to include it.

I tried but my app is crashed after this...

Please help me

**Comment by gduflo** [comment]
I don't know if this the same case as mine, but for me, ```getCamera()``` returns ```null```. So if it the case for you as well, it is normal it crashes since ```setFocusMode(...)``` is applied on a ```null``` object.

By the way, if you have solved this problem, I am interested by your solution.

**Comment by gduflo** [comment]
If your problem was that ```getCamera()``` returns ```null```: https://github.com/DJI-Mobile-SDK-Tutorials/Android-FPVDemo/issues/34#issuecomment-436585696
