### ISSUE TITLE
SDK Lib is build with android level 22

### ISSUE THREAD

**Issue by alexbuicescu** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#4]
You should mention in the README that the sdk is built with android level 22, because the project must also be built with android level 22. By default android studio creates a project using the latest built tools (at the moment it would be compileSdkVersion 23).

Also, the sample project android level is 23 so it won't run successfully.

**Comment by dji-dev** [comment]
Hi, we have tested the demo on Android Studio, and it works well. Here are the project settings:

- Android Studio 1.5.1
- API level 23

<img width="1680" alt="unknown" src="https://cloud.githubusercontent.com/assets/11869194/13035570/6a7e8c86-d308-11e5-85b6-c0dfefffe4aa.png">

Please try with these settings. Hope it helps!

**Comment by cornicione** [comment]
there is a problem when I run this demo, i even can't register successfully.
A error log keep saying that  E/DJIVideoDecoder: dequeueOutputBuffer codec null

**Comment by dji-dev** [comment]
If you can't register, please make sure your app API_KEY is correctly declared in Manifest file.
