### ISSUE TITLE
4.11 build crashing randomly.

### ISSUE THREAD

**Issue by flythecode** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#42]
Think 4.11.1 fixed the problem. Need to change to 4.11.1 not 4.11

**Comment by flightxar** [comment]
Android PIE, Samsung TAB S4

**Comment by flightxar** [comment]
4.11 and 4.10 same problem

**Comment by jeryini** [comment]
I was also having issue with 4.11, it was crashing after I tried opening video. Now it works perfectly after I bumped version from 4.11 to 4.11.2 in `build.gradle`.
