### ISSUE TITLE
Error when capturing from camera on Mavic 2 Enterprise

### ISSUE THREAD

**Issue by g-spacewhale** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#43]
After app deployment using our api key, the app starts and connects to the mavic 2.
The live video feed works, but when trying to record a video or take a capture, the error
`"dji error camera is busy or the command is not supported in the current state"

gets thrown.
Is there a workaround, which allows image capture during live video stream for the mavic 2?

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/31423'>Zendesk ticket #31423</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Please check if it can work in the DJI GO 4 App.

This issue will happen in the following cases:
-SD card was not installed
-SD card is full

Yes, we have a workaround to capture the image, the YUV data, from the live video stream, please refer to this documentation:
https://developer.dji.com/mobile-sdk/documentation/sample-code/index.html

Thanks,

Luce Luo
DJI Dev Team

**Comment by g-spacewhale** [comment]
Thank you for your response, it was indeed not possible to take photos on the DJI Pilot Android app as well. The error came up even though:

- the internal storage and sd card where both empty
- an SD card was installed
- the drone was not connected to a computer via cable for data read out

Reformatting the internal storage via the DJI Pilot app solved the problem.
