### ISSUE TITLE
Display Image in OpenCV

### ISSUE THREAD

**Issue by manuoso** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#45]
Hi,

There is some simple way to decode the received H264 raw image to display it in OpenCV, without using DJI decoder?

Thanks in advance.

**Comment by dji-dev** [comment]
Agent comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/34127'>Zendesk ticket #34127</a>:<br><br>DJI Developer Support engineers will be on holiday for the international worker's day (5-1 ~ 5-5), which may cause some delays in responding to your issue.

Best Regards,
DJI SDK Support Team



Join DJI's Developer Community in our new Forum for Technical Discussions, Announcements and More:
https://forum.dji.com/forum-139-1.html?from=developer

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34127'>Zendesk ticket #34127</a>:<br><br>Dear Client
Thank you for contacting DJI.

For video streaming you can get H264 stream and put them into H264. You can see the details in
https://github.com/DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
