### ISSUE TITLE
Question about Thermal Image reference frame

### ISSUE THREAD

**Issue by mgrova** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#46]
Hello, I am writing to ask you about the reference system of the thermal camera of the Mavic 2 Dual Enterprise.

I'm looking at your documentation and I can't find anything about it. The system you use is as follows? Where the ranges of the X and Y axes are [0-1].

![Untitled Diagram](https://user-images.githubusercontent.com/29304573/80962049-8fb55980-8e0c-11ea-94b6-37726895baab.png)

Thanks in advance and best regards !

**Comment by dji-dev** [comment]
Agent comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/34182'>Zendesk ticket #34182</a>:<br><br>Our DJI Developer Support agents will be on holiday for the international worker's day (5-1 ~ 5-5), which may cause some delays in responding to your issue. Thank you for you understanding and we will answer you as quickly as possible.

Join DJI's Developer Community in our new Forum for Technical Discussions, Announcements and More:
https://forum.dji.com/forum-139-1.html?from=developer

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34182'>Zendesk ticket #34182</a>:<br><br>Dear Client
Thank you for contacting DJI.

Hi, we saw you have closed the issue. We assume you have came up with an answer. If not please reopen the issue and contact us again. Good luck for your future development.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
