### ISSUE TITLE
can't connect to remote control

### ISSUE THREAD

**Issue by smellok** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#7]
run demo code, can't connect to remote control.

m100,firmware:v1.5.8

the app-key is correct and pass the sdk validation.

**Comment by bendarwing** [comment]
I'm having the same issue. Wifi does work but RC doesn't.

**Comment by oliverou** [comment]
Hi @smellok , @bendarwing , we just update the FPVDemo to Android SDK 4.1, could you try again and check if the issue still exist? @bendarwing , which DJI product do you use for testing?

**Comment by xbting** [comment]
Mine is phantom-4-adv,have the save issue.
register success,but startConnectionToProduct return false

**Comment by oliverou** [comment]
Hi @xbting , for Phantom 4 Advanced, the latest Android SDK 4.1 has supported, and the FPVDemo has just been updated to SDK 4.1. Please clone the latest version of FPVDemo and try again. Thanks!
