### ISSUE TITLE
Phone has no SD Card

### ISSUE THREAD

**Issue by GitPlz** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#8]
The video recording and image capturing doesn't work on phones that don't have SD cards.

**Comment by dji-dev** [comment]
Hi, it should work even your android device don't have SD cards. To capture photo and record video, you must insert an SD card in the camera of the drone.

If it still doesn't work, could you tell me the following items:
1. Which android device and Android System you are using? 
2. Which version of Android Studio are you using? 
3. Which DJI Drone you are using to run the FPVDemo?
Thanks!

**Comment by oliverou** [comment]
Since there is no response from @GitPlz for a long time, close this issue now.
